### ISSUE TITLE
拖入rar后一定概率崩溃

### ISSUE THREAD

**Issue by catshitz** [SingleVrUser/Helper_1080#2]
Helper_1080_v0.1.1
先读一个rar 再拖入另一个rar后崩了 补充：又试了几个 有时新打开拖入rar也不确定地崩溃
大佬这个读百度QR OCR很好用 感觉更好的实现方式是greasyfork的js脚本
就是不知行不行得通(因为涉及到OCR估计不好办)
但现在的微软应用感觉稳定性差点 主要每读一个都怕崩溃 要重开有点麻烦 且略微简陋😅

**Comment by SingleVrUser** [comment]
winui3目前还不是很稳定。拖入文件有几率会崩溃
[microsoft-ui-xaml/issues/7007](https://github.com/microsoft/microsoft-ui-xaml/issues/7007)
或许以后微软会修复这个BUG吧😜
不过为什么不 一次拖入所有的压缩包，一个一个拖不是很麻烦吗？

之前还想着用论坛和百度/115的接口实现一键转存的，不过现在还没空实现，只做了简单的版本

js也是个好方法，我有空学习一下😁

**Comment by catshitz** [comment]
专项一键转存好啊 不过估计轮子有点大不太好实现 感觉跟js更沾边 不过py也不是不可以
主要搜集旧作时是一个一个找的 所以一个一个拖 比起找好在一口气拖入更准确点不易出错
现在也能用就先这样用着吧 期待日后有更好的脚本👍
